openapi: 3.0.1
servers:
  - url: '{protocol}://www.thebodgery.com/api'
    variables:
      protocol:
        description: 'The Bodgery API is accessible via https and http'
        enum:
          - https
          - http
        default: https
info:
  description: >-
    The Bodgery api allows users to query access many programatic functions 
    related to The Bodgery makerspace in Madison, WI. These functions include
    querying Wild Apricot for current member status and tool checkoff status.
    It also includes task management functions. More functionality to be added 
    as needed.
  version: 1.0.0
  title: Bodgery API
  contact:
    name: James Pittman
    email: cnc@thebodgery.org
tags:
  - name: Tasks
    description: Manage shop related tasks
  - name: Members
    description: Get member status
  - name: Tools
    description: Get Tool info
  - name: Telemetry
    description: 'Get telemetry information such as temp, air quality, or 
    shop open status'
paths:
  /tasks:
    get:
      tags:
        - Tasks
      operationId: listTasks
      summary: List available tasks
      responses:
        '200':
          description: Returns a list of tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/taskList'
              example:
                {
                  tasks:[
                    {
                      "id": "0",
                      "name": "Empty trash into bins",
                      "description": "All inside trash and recycling bins should be emptied into the large rolling bins outside the building"
                    },
                    {
                      "id": "1",
                      "name": "Take bins to curb",
                      "description": "Outside rolling trash bins should be taken to the curb every week on Tuesday. Recycling should be taken to the curb every other Tuesday."
                    }
                  ]
                }
components:
  schemas:
    taskList:
      type: array
      items:
        $ref: '#/components/schemas/task'
    task:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          maxLength: 50
        description:
          type: string
          maxLength: 8000
          